INSERT INTO tb_autores (nome) VALUES ('Machado de Assis');
INSERT INTO tb_autores (nome) VALUES ('Clarice Lispector');
INSERT INTO tb_autores (nome) VALUES ('Jorge Amado');
INSERT INTO tb_autores (nome) VALUES ('Graciliano Ramos');
INSERT INTO tb_autores (nome) VALUES ('José de Alencar');
INSERT INTO tb_autores (nome) VALUES ('Carlos Drummond de Andrade');
INSERT INTO tb_autores (nome) VALUES ('Vinicius de Moraes');
INSERT INTO tb_autores (nome) VALUES ('Cecília Meireles');
INSERT INTO tb_autores (nome) VALUES ('Fernando Pessoa');
INSERT INTO tb_autores (nome) VALUES ('Luís de Camões');
INSERT INTO tb_autores (nome) VALUES ('Castro Alves');
INSERT INTO tb_autores (nome) VALUES ('Olavo Bilac');
INSERT INTO tb_autores (nome) VALUES ('Augusto dos Anjos');
INSERT INTO tb_autores (nome) VALUES ('Monteiro Lobato');
INSERT INTO tb_autores (nome) VALUES ('Érico Veríssimo');
INSERT INTO tb_autores (nome) VALUES ('Lima Barreto');
INSERT INTO tb_autores (nome) VALUES ('Guimarães Rosa');
INSERT INTO tb_autores (nome) VALUES ('Rachel de Queiroz');
INSERT INTO tb_autores (nome) VALUES ('José Saramago');
INSERT INTO tb_autores (nome) VALUES ('Gabriel García Márquez');
INSERT INTO tb_autores (nome) VALUES ('Pablo Neruda');
INSERT INTO tb_autores (nome) VALUES ('Miguel de Cervantes');
INSERT INTO tb_autores (nome) VALUES ('William Shakespeare');
INSERT INTO tb_autores (nome) VALUES ('Jane Austen');
INSERT INTO tb_autores (nome) VALUES ('Charles Dickens');
INSERT INTO tb_autores (nome) VALUES ('Leo Tolstoy');
INSERT INTO tb_autores (nome) VALUES ('Virginia Woolf');
INSERT INTO tb_autores (nome) VALUES ('Jean-Paul Sartre');
INSERT INTO tb_autores (nome) VALUES ('Albert Einstein');
INSERT INTO tb_autores (nome) VALUES ('Stephen Hawking');
INSERT INTO tb_autores (nome) VALUES ('Isaac Newton');
INSERT INTO tb_autores (nome) VALUES ('Galileo Galilei');
INSERT INTO tb_autores (nome) VALUES ('Marie Curie');
INSERT INTO tb_autores (nome) VALUES ('Alan Turing');
INSERT INTO tb_autores (nome) VALUES ('Bill Gates');
INSERT INTO tb_autores (nome) VALUES ('Steve Jobs');
INSERT INTO tb_autores (nome) VALUES ('Mark Zuckerberg');
INSERT INTO tb_autores (nome) VALUES ('Elon Musk');
INSERT INTO tb_autores (nome) VALUES ('Jeff Bezos');
INSERT INTO tb_autores (nome) VALUES ('Mahatma Gandhi');
INSERT INTO tb_autores (nome) VALUES ('Martin Luther King Jr.');
INSERT INTO tb_autores (nome) VALUES ('Nelson Mandela');
INSERT INTO tb_autores (nome) VALUES ('Madre Teresa');
INSERT INTO tb_autores (nome) VALUES ('Dalai Lama');
INSERT INTO tb_autores (nome) VALUES ('Papa Francisco');
INSERT INTO tb_autores (nome) VALUES ('Buda');
INSERT INTO tb_autores (nome) VALUES ('Confúcio');
INSERT INTO tb_autores (nome) VALUES ('Sócrates');
INSERT INTO tb_autores (nome) VALUES ('Platão');
INSERT INTO tb_autores (nome) VALUES ('Aristóteles');

INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('A Hora da Estrela', 2, 1977);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Memórias Póstumas de Brás Cubas', 1, 1881);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Gabriela, Cravo e Canela', 3, 1958);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Dom Casmurro', 1, 1899);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Alguma Poesia', 6, 1930);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Poesias', 12, 1916);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('O Caminho Para a Poesia', 7, 1970);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Viagem', 8, 1939);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Mensagem', 9, 1934);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Os Lusíadas', 10, 1572);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Espumas Flutuantes', 11, 1870);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Vidas Secas', 4, 1938);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Eu', 13, 1915);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Urupês', 14, 1914);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Grande Sertão: Veredas', 17, 1956);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('O Tempo e o Vento', 15, 1949);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Triste Fim de Policarpo Quaresma', 16, 1915);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Vinte Poemas de Amor e Uma Canção Desesperada', 21, 1924);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Oliver Twist', 25, 1838);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Orgulho e Preconceito', 24, 1813);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Ensaio Sobre a Cegueira', 19, 1995);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Guerra e Paz', 26, 1869);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Cem Anos de Solidão', 20, 1967);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Steve Jobs', 36, 2011);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Dom Quixote', 22, 1605);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Hamlet', 23, 1603);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Teoria da Relatividade', 29, 1905);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Iracema', 5, 1865);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Mrs. Dalloway', 27, 1925);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('O Quinze', 18, 1930);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Uma Breve História do Tempo', 30, 1988);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('O Ser e o Nada', 28, 1943);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('O Teste de Turing', 34, 1950);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Radioatividade', 33, 1903);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('A Autobiografia de Mahatma Gandhi', 40, 1927);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('The Road Ahead', 35, 1995);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Sidereus Nuncius', 32, 1610);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Ética a Nicômaco', 50, -350);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('A História do Facebook', 37, 2010);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Eu Tenho um Sonho', 41, 1963);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Longa Caminhada para a Liberdade', 42, 1994);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('A Loja de Tudo', 39, 2013);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Philosophiæ Naturalis Principia Mathematica', 31, 1687);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('O Livro da Compaixão', 44, 2001);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('A República', 49, -380);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Um Caminho Simples', 43, 1995);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('A Alegria do Evangelho', 45, 2013);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Elon Musk: Tesla, SpaceX e o Futuro', 38, 2015);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('O Dhammapada', 46, -483);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Apologia de Sócrates', 48, -399);
INSERT INTO tb_livros (titulo, autor_id, ano_publicacao) VALUES ('Os Analectos', 47, -479);

INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (2, 'João Pereira', '2025-01-10', NULL);
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (1, 'Ana Silva', '2025-01-15', '2025-01-22');
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (4, 'Carlos Souza', '2025-01-18', NULL);
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (3, 'Maria Oliveira', '2025-01-20', NULL);
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (5, 'Pedro Santos', '2025-01-25', '2025-02-01');
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (7, 'Fernanda Costa', '2025-02-05', NULL);
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (9, 'Lucas Almeida', '2025-02-10', '2025-02-17');
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (12, 'Isabela Ribeiro', '2025-02-15', NULL);
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (15, 'Rafael Martins', '2025-02-20', '2025-02-27');
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (18, 'Juliana Barbosa', '2025-03-01', NULL);
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (20, 'Thiago Ferreira', '2025-03-05', '2025-03-12');
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (23, 'Camila Castro', '2025-03-10', NULL);
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (26, 'Bruno Gomes', '2025-03-15', '2025-03-22');
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (29, 'Amanda Lima', '2025-03-20', NULL);
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (32, 'Gustavo Pereira', '2025-04-01', '2025-04-08');
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (35, 'Patricia Silva', '2025-04-05', NULL);
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (38, 'Marcelo Souza', '2025-04-10', '2025-04-17');
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (41, 'Aline Oliveira', '2025-04-15', NULL);
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (44, 'Roberto Santos', '2025-04-20', '2025-04-27');
INSERT INTO tb_emprestimos (livro_id, usuario, data_emprestimo, data_devolucao) VALUES (47, 'Tatiana Costa', '2025-05-01', NULL);